# To automatically format code on push using Prettier

name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  prettier:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Prettier Action
      - uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/*.{js, vue}
